# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forgeguardian < Formula
  desc "AI-powered supply chain security scanner for software packages"
  homepage "https://github.com/mah3sec/forgeguardian"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mah3sec/forgeguardian/releases/download/v1.0.0/forgeguardian_1.0.0_darwin_amd64.tar.gz"
      sha256 "38c3d222084a85a3dade3d7897832676bcc4be2c27a8bc4e95351b1093006aed"

      define_method(:install) do
        bin.install "fgctl"
        bin.install "fg-agent"
        bin.install "intel-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mah3sec/forgeguardian/releases/download/v1.0.0/forgeguardian_1.0.0_darwin_arm64.tar.gz"
      sha256 "5fcb09577c35325ccd25a6a0187be17c139aa2e8d946665a1d77792383918287"

      define_method(:install) do
        bin.install "fgctl"
        bin.install "fg-agent"
        bin.install "intel-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mah3sec/forgeguardian/releases/download/v1.0.0/forgeguardian_1.0.0_linux_amd64.tar.gz"
      sha256 "06a2cdb4e4b0538d660dab5c9d6eb0ea3d5df0a3d6bf30ff2870d272d8b454e9"
      define_method(:install) do
        bin.install "fgctl"
        bin.install "fg-agent"
        bin.install "intel-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mah3sec/forgeguardian/releases/download/v1.0.0/forgeguardian_1.0.0_linux_arm64.tar.gz"
      sha256 "fe8894d28b59544071d49b9ad544d60692f443fb91bee1fd81c25b39fb52d99d"
      define_method(:install) do
        bin.install "fgctl"
        bin.install "fg-agent"
        bin.install "intel-agent"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fgctl version")
  end
end
