# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forgeguardian < Formula
  desc "AI-powered supply chain security scanner for software packages"
  homepage "https://github.com/mah3sec/forgeguardian"
  version "0.1.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mah3sec/forgeguardian/releases/download/v0.1.4/forgeguardian_0.1.4_darwin_amd64.tar.gz"
      sha256 "81d4eb04690e997811c4697f5189948ac445100b758987b530d1f36734df01bb"

      define_method(:install) do
        bin.install "fgctl"
        bin.install "fg-agent"
        bin.install "intel-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mah3sec/forgeguardian/releases/download/v0.1.4/forgeguardian_0.1.4_darwin_arm64.tar.gz"
      sha256 "ea60cca6ed8c225ce14b3a005d6a903fb3d2f7913d58aad784c98490aadfb567"

      define_method(:install) do
        bin.install "fgctl"
        bin.install "fg-agent"
        bin.install "intel-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mah3sec/forgeguardian/releases/download/v0.1.4/forgeguardian_0.1.4_linux_amd64.tar.gz"
      sha256 "0dbd20926f73bd48022f6e84b86f180503fb18c3d2e0aa8111523ddb31223675"
      define_method(:install) do
        bin.install "fgctl"
        bin.install "fg-agent"
        bin.install "intel-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mah3sec/forgeguardian/releases/download/v0.1.4/forgeguardian_0.1.4_linux_arm64.tar.gz"
      sha256 "97c04edd5b01765b792e150767654f403d35c242295c50e494e4f7f2ee8ef78d"
      define_method(:install) do
        bin.install "fgctl"
        bin.install "fg-agent"
        bin.install "intel-agent"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fgctl version")
  end
end
