# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forgeguardian < Formula
  desc "AI-powered supply chain security scanner for software packages"
  homepage "https://github.com/mah3sec/forgeguardian"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mah3sec/forgeguardian/releases/download/v1.0.0/forgeguardian_1.0.0_darwin_amd64.tar.gz"
      sha256 "5e0a9b157757919cf88a2571208e9044ec3ec18eb217adf4df3300d1f6406ac0"

      define_method(:install) do
        bin.install "fgctl"
        bin.install "fg-agent"
        bin.install "intel-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mah3sec/forgeguardian/releases/download/v1.0.0/forgeguardian_1.0.0_darwin_arm64.tar.gz"
      sha256 "c72ef066158b2dc417c19131ad4b094f09f946391649537747f31ff3bd1839f2"

      define_method(:install) do
        bin.install "fgctl"
        bin.install "fg-agent"
        bin.install "intel-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mah3sec/forgeguardian/releases/download/v1.0.0/forgeguardian_1.0.0_linux_amd64.tar.gz"
      sha256 "302dd1cffce007d3ecbb1f4a9dd8f911f0e61c7d974a20590241cf712de3ea21"
      define_method(:install) do
        bin.install "fgctl"
        bin.install "fg-agent"
        bin.install "intel-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mah3sec/forgeguardian/releases/download/v1.0.0/forgeguardian_1.0.0_linux_arm64.tar.gz"
      sha256 "528d3d0192531eaeeee65e8b7b49f4ad1f19dca2be22e498cef80b0a4fa2e6e9"
      define_method(:install) do
        bin.install "fgctl"
        bin.install "fg-agent"
        bin.install "intel-agent"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fgctl version")
  end
end
